version: '3.4'
services:
  mysql:
    image: mysql:8.0
    env_file: 
      - ./.env
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
  # mongo:
  #   image: mongo:5.0.2
  #   env_file: 
  #     - ./.env
  #   volumes:
  #     - database:/usr/local/var/mongodb
  #   ports:
  #     - '27017:27017'
  reservations:
    # depends_on:
    #   - mongo
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
  auth:
    # depends_on:
    #   - mongo
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  payments:
    # depends_on:
    #   - mongo
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
  notifications:
    # depends_on:
    #   - mongo
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
volumes:
  database: