version: '3.3'
services:
  e2e:
    depends_on:
      - mongo
      - reservations
      - auth
      - payments
      - notifications
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
  mongo:
    image: mongo:5.0.2
    env_file: 
      - ../.env
    volumes:
      - database:/usr/local/var/mongodb
    ports:
      - '27017:27017'
  reservations:
    depends_on:
      - mongo
    image: us-east4-docker.pkg.dev/sleepr-427713/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    depends_on:
      - mongo
    image: us-east4-docker.pkg.dev/sleepr-427713/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    depends_on:
      - mongo
    image: us-east4-docker.pkg.dev/sleepr-427713/payments/production
    env_file:
      - ../apps/payments/.env
  notifications:
    depends_on:
      - mongo
    image: us-east4-docker.pkg.dev/sleepr-427713/notifications/production
    env_file:
      - ../apps/notifications/.env
volumes:
  database: